### ISSUE TITLE
immediate shutdown by permission denied

### ISSUE THREAD

**Issue by K4zuki** [mintty/wsltty#135]
### Condition
""
* Windows 10 1803
* wsltty 1.9.3 and 1.9.5
* `wsl.conf` is edited as following

```ini
[automount]
root = /
options = "metadata,umask=22,fmask=111"
```

### Problem

* (as titled) it immediately closes
* error message is as following

```
/bin/wslbridge: Exit 1.
wslbridge error: failed to start backend process
note: backend error output: /bin/bash: /c/Users/kyama/AppData/Local/wsltty/bin/wslbridge-backend: Permission denied
```

* similar error message with #91 ("Not found" vs. "Permission denied")
* seems mount option matter: removing 3rd line fixes(as fixed by #91)

**Comment by K4zuki** [comment]
`chmod +x` worked. thanks!

**Comment by mintty** [comment]
@Biswa96: this seems related to the explicit placement of the backend for the sake of the appx version,
however the "normal" version wouldn't really need it.
If you copy wslbridge-backend to the WSL /bin directory, does it work then?
(Maybe not, because wslbridge now addresses the copy by absolute pathname, to be checked.)

**Comment by Biswa96** [comment]
The C# launcher in Appx package does place the wslbridge-backend in that path. Hence not related with mintty binary.
