### ISSUE TITLE
Wsltty does not automatically wrap/unwrap the text 

### ISSUE THREAD

**Issue by Po-wei** [mintty/wsltty#154]
When adjust the window size, wsltty only adjust the last line of text,
while the native wsl terminal adjust all text in the window.

For example,
![image](https://user-images.githubusercontent.com/17596021/53148721-916b7680-35e6-11e9-89e0-d87059ad440f.png)

WSLtty after adjust the width
![image](https://user-images.githubusercontent.com/17596021/53148757-ac3deb00-35e6-11e9-9a72-684777b3b91b.png)

native wsl terminal
![image](https://user-images.githubusercontent.com/17596021/53148885-122a7280-35e7-11e9-8ffd-babe59e84b29.png)

This is also applied to expand the window.

**Comment by mintty** [comment]
Apparently the native tty rewraps lines after resizing. While some terminals support that feature, it is not a traditional terminal feature. E.g. xterm does not support it. It was requested for mintty already in mintty/mintty#82.

**Comment by beginrescueend** [comment]
I just found MinTTY today for WSL and already love it! Thanks for your work!

I think this would be a wonderful feature, myself.

I think this feature is called Text Reflow, available in iTerm 2 for MacOS and in both Gnome Terminator and Gnome Terminal for Linux.

I don't know if it's an "easy" enhancement, since upon a resize (possibly "WINCH" signal,) you'd have to look backward and possibly forward in the scrollback, in order to resize lines.

I wonder if source code for iTerm, Terminator, or Gnome Terminal could reveal an easy way to do Text Reflow.

(If implemented, it should be something that can be turned off and on in "Options." I could see people either loving it or hating it, depending on their situation.)
