### ISSUE TITLE
checksum for the binary release

### ISSUE THREAD

**Issue by luyoutao** [mintty/wsltty#189]
Just to ensure the file integrity--can you please provide checksum for your binary release? Thanks.

**Comment by mintty** [comment]
I may be ignorant, but what's the purpose of a checksum for a github download? Do you think you could be spoofed about github.com?
Also, how would a typical checksum be generated? (Cygwin tool and parameters please.)

**Comment by Biswa96** [comment]
* In cygwin, we have shasum, sha224sum, sha256sum, sha384sum, sha512sum.
* In powershell, [Get-FileHash](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/get-filehash).

**Comment by mintty** [comment]
Checksum for the current release, if that's what you're up to:
> shasum -b wsltty-3.0.2.3-install.exe

07e1f0c04589967b013d977f5a36ae8a48a0cc85 *wsltty-3.0.2.3-install.exe

**Comment by Biswa96** [comment]
I think OP wants to provide SHA256 (or higher) in release page.

**Comment by mintty** [comment]
I see no point in that. What's the value? If someone really spoofs a github page in order to spread a maliciously manipulated download, they can as well publish a modified checksum. Placing a checksum aside only gives a false impression of security which is not given.
A checksum may be used in mailing list announcements but it's even counter-productive to publish a checksum along with the download.

**Comment by luyoutao** [comment]
@mintty What you said makes sense. But in general, how to prevent a binary release from being tampered?

**Comment by mintty** [comment]
Closing as general security questions cannot be answered here. Thanks for raising the issue.
