### ISSUE TITLE
How to update mintty/wsltty?

### ISSUE THREAD

**Issue by gaia** [mintty/wsltty#20]
How do I update mintty, and how do I update wsltty?

If possible, How do I schedule an update check for the two?

**Comment by mintty** [comment]
There is no update check available.
Mintty updates are integrated in wsltty updates, there would be no separate update anyway.

You could build wsltty yourself and update the mintty version in the makefile. Build environment is cygwin (32 bit).

I could perhaps build an "update available" check into the About popup of mintty, if that's desired.

**Comment by gaia** [comment]
That would be desirable. For now I have to manually track whether it is updated and re-install the new version, correct?

**Comment by mintty** [comment]
I could check the version against a file from the mintty repository or home page.
But I'd need to retrieve a URL with Windows functions (to avoid proxy configuation if using cygwin functions). It would help if someone provides suitable code using a function like URLOpenStream or HttpOpenRequest.

**Comment by mintty** [comment]
"thumbs up" means you're going to provide such a code sniplet?

**Comment by gaia** [comment]
I would if I could. Sorry.

**Comment by mintty** [comment]
Just had the bold idea that somebody could make a Debian package to deploy wsltty. Whether it's possible by the respective package policy to deploy software that is not compiled under Debian, I don't know. Also "somebody" would not be me in this case.

**Comment by tkelman** [comment]
Does Debian have cygwin cross-compilers available? That could conceivably work too, maybe? I've heard that Fedora does or did have cygwin cross-compilers, but haven't tried using them myself. And Fedora doesn't help too much for users of WSL. Someone could make a PPA perhaps, where the policies are a bit less stringent.

**Comment by ChrisM-Rogers** [comment]
@mintty Just a thought, if you included a version file, or specified the version in a file with the releases of this, you could then maybe add a shell script to the user's home directory which would simply `wget` or `curl` the `makefile` hosted here and then `cat` it, `grep` and regex it, or just regex it for the version number, compare with the current and `echo` (No) New updates. The the user can just run it when they want to check. 

Not anything spectacular, but it does the job.

**Comment by ChrisM-Rogers** [comment]
Another alternative is to provide another bat that’s added to the start menu and maybe use something like [this](https://stackoverflow.com/questions/4619088/windows-batch-file-file-download-from-a-url) to obtain the `makefile`, then you could use the `findstr` command (accepts regex too) and use that for comparison?

**Comment by mintty** [comment]
I had thought about bundling wget or curl with wsltty as you suggest, for an instant...
That would be an easy solution if it worked. However, bare the question of library dependencies pulled in, they would not consider the proxy as configured for Windows, and I don't wish to have additional proxy configuration in mintty just for this purpose. That's why using a Windows API function is a more feasible approach. That won't be really hard, just a little bit tricky because of the quirks of Windows callback APIs, and I didn't feel like doing it myself. Oh, and the call should probably be threaded, not to block mintty.
Something like retrieve_text_from_url(url), returning immediately and when a bit of text (e.g. a line) has been downloaded, send it to `wnd` via a message (like SendMessage(wnd, WM_SYSCOMMAND, IDM_DOWNLOAD, text).

**Comment by tkelman** [comment]
writing something in powershell would be simpler

**Comment by mintty** [comment]
Is Powershell always installed by default now?
If it is, and you provide a script, I will integrate it.

**Comment by tkelman** [comment]
since vista, yeah

**Comment by mintty** [comment]
(googled) It seems to be basically simple, even though the simple form (using HtmlWebResponseObject) seems to work only for newer versions of Powershell. Is it possible to make this HtmlWebResponseObject send a message to a window? Anyway, stuffing a file would also work. Yet the thing needs to be invoked, asynchronously, and preferably not popup on the screen. Since I'm not into Powershell, I would appreciate if someone demonstrates that for me.

**Comment by tkelman** [comment]
wsl is a win10 feature, so I think you can rely on fairly recent powershell

not sure about the exact implementation details here myself. whatever invokes powershell to run the script could probably background that task?

**Comment by mintty** [comment]
This one-liner works:
`(new-object System.Net.WebClient).DownloadFileAsync("url", "file")`
and doesn't need Powershell 3; it seems to need `.net`, don't know what happens if that's not installed.
The description of the [WebClient](https://msdn.microsoft.com/en-us/library/system.net.webclient%28v=vs.110%29.aspx) class suggests it should also be possible to invoke that without starting a Powershell externally, which might save some delay. I would appreciate to use either function `DownloadStringAsync(Uri)` or `DownloadStringAsync(Uri, Object)` of that class, but I don't know how to create, initialize and invoke such a class from a C program; also result of the asynchronous call is delivered with some message which would need to be captured, to store the result in some string.
If someone provides a sample implementation along this approach, that would be great.

**Comment by ChrisM-Rogers** [comment]
Sorry I dropped my comms, been busy with my server over the weekend.

I've done a couple of things in C, I'm no genie but I could try an knock something up for you? No guarantee though. I was thinking, if it's going to be done in a language (i.e. C) and built into the application itself, there should be no need for the use of Powershell either as it would be faster to do it natively in the application itself.

I'm a little busy at work right now, but I'll try and get back to you with an example later.

**Comment by mintty** [comment]
I've implemented an update checker. With some setup tricks, you could try it: compile the current mintty repository version in a Cygwin 32-bit environment, then replace the binaries (possibly also an updated cygwin1.dll) in the wsltty hierarchy.
The update checks every time the Options menu is opened. That may be too often, which could still be tuned. Also I guess I should make the whole procedure optional as some people may not favour unsolicited Internet contact.
Comments welcome.

**Comment by mintty** [comment]
Released with 0.7.5 (referring to mintty version, now 2.7.5).

**Comment by ADTC** [comment]
I'm seeing the update notification in the title bar. How do I update though? There is no binary installer to download.

![mintty-update](https://user-images.githubusercontent.com/6047296/30914992-ef2318ea-a3b2-11e7-93ed-75e75f245540.png)

I'm on 2.7.7

**Comment by mintty** [comment]
You would download the latest release installer of wsltty and simply install it over your current version.

**Comment by mintty** [comment]
The next release shall refer to the wsltty version rather than the mintty version.

**Comment by mintty** [comment]
Released 1.8.0.

**Comment by tweakimp** [comment]
Can you make the update notification clickable to it leads you to the download site? :)

**Comment by mintty** [comment]
It's not easy to capture such a click. Maybe the WM_NCHITTEST message in windialog.c would work. But it's not possible to limit handling to exact position of the hint text, so any click on the top border would trigger the link opening.
