### ISSUE TITLE
wsltty takes a long time to open new windows since 3.1.0

### ISSUE THREAD

**Issue by jmunsin** [mintty/wsltty#221]
I updated to 3.1.0.2 (x86_64) from 3.0.6 and noticed it now takes 2-3 seconds to open a wsltty window. Tried 3.1.0 and it is also slower. Tried 3.1.0.2 (i686) with no improvment. Downgraded back to 3.0.6, and it still works as before, new wsltty windows are opened in < 1s.

**Comment by Biswa96** [comment]
Try to open a wsl.exe window first then open wsltty latest version with same distribution, does it seem to be faster now?

**Comment by jmunsin** [comment]
No, that does seem to make any difference.

**Comment by Biswa96** [comment]
I don't see any big difference of launch time in my PC. There is no difference between wsltty version 3.1.0.2 (x86_64) and 3.0.6 in my case. In wslbridge2, I have tried to squeeze every bit of performance, for example using Windows sockets instead of Cygwin. The source code can be found here [wslbridge2](https://github.com/Biswa96/wslbridge2).

Sometimes anti-virus or anti-malware programs may slow down it. Also check if shell rc files (.bashrc, .zshrc etc.) cause any issue. Do you have any way to measure the time?

**Comment by Biswa96** [comment]
Thank you for the verification. You can close your issue. There is no restriction.
