### ISSUE TITLE
Unable to execute certain commands

### ISSUE THREAD

**Issue by bluretrece** [mintty/wsltty#228]
Hi! I'm loving the terminal so far, I've been working for a few days with it and and I found it smoother than other terminals. However, whenever I try to run commands such as "cargo new helloworld", the terminal is complaining about that the command "cargo" was not found, in other hand, if I run the standard WSL the commands works perfectly. The same issue happens with other commands that the standard WSL is able to recognize. Am I missing any additional configuration? I would deeply appreciate any help. Thanks in advance.

**Comment by bluretrece** [comment]
Sorry for closing and opening again. I was able to solve this issue by executing the configure "WSL shortcuts" script.

**Comment by Biswa96** [comment]
This happens because wsltty (really wslbridge) does not open shell with login mode by default but wsl.exe does. Also the cargo path is appended in `.bash_profile` or `.profile` which is read by bash when executed as login shell [bash(1)](https://linux.die.net/man/1/bash). The shortcuts has that login option `-l` to open shell with login mode.
