### ISSUE TITLE
Window restore size not sticking

### ISSUE THREAD

**Issue by eggbean** [mintty/wsltty#244]
A long-standing irritation which I still haven't found the solution for is how alt-enter full-screen toggle sometimes starts restoring to not the window size in settings, or the previous window size, but one that is nearly the size of the full screen.  I then have to resize the window.

How do I stop this from happening?

**Comment by mintty** [comment]
I've had occasional size glitches when for example moving a window to another screen (esp. of different resolution), or toggling the scrollbar. However restoring to near-full-screen instead of window size has never happend for me.
Please describe the issue more pecisely. What are sizes before full-screen, while full-screen, after restore? Any other special settings on your side?

**Comment by eggbean** [comment]
I still don't know what is causing this, but it's also happening with kitty (putty fork), so clearly has nothing to do with wsltty itself.
