### ISSUE TITLE
Window stuck always on top

### ISSUE THREAD

**Issue by krashekspres** [mintty/wsltty#47]
If I press ctrl+[shift]+tab window gets stuck always on top, I have to minimize or close it to view windows behind.

**Comment by mintty** [comment]
Hmm. Probably a side-effect of fixing mintty/mintty#652.

**Comment by mintty** [comment]
Released 0.7.8.

**Comment by konrad-schwarz** [comment]
I have the same problem -- Windows always on top of the z order.  I'm not sure how to trigger it, perhaps using ctrl+shift+tab.

Options->About reports mintty 2.8.1 (x86_64-pc-cygwin).  I'm unsure how this relates to the version mentioned in the above comment "0.7.8".  Should this bug be fixed in my version?

**Comment by mintty** [comment]
Did you use the new session switcher feature (from the extended context menu)?

**Comment by mintty** [comment]
Please report a precise, short sequence (begin with starting mintty windows) to produce the issue because "the same problem" does not really help debugging 4 releases later.

**Comment by konrad-schwarz** [comment]
I will report back when I have identified such a sequence.
