### ISSUE TITLE
New installation with windows store WSL, 'Cannot find distribution'

### ISSUE THREAD

**Issue by krazyito65** [mintty/wsltty#72]
When I do a new / clean install of WSL using the windows store it cannot open correctly becasue it 'can't find a distribution'.  Will wsltty be supported for this new version of WSL?

**Comment by krazyito65** [comment]
https://i.imgur.com/v2H8JNK.png  -- here is an image of the error in front of the WSL Ubuntu terminal

**Comment by krazyito65** [comment]
https://github.com/mintty/wsltty/issues/64  -- i found this to be similar, though for me i did a 'clean install' of windows (using the reset windows option) and this still happened.

**Comment by mintty** [comment]
I assume you clicked the desktop shortcut "WSL Terminal"?
After adding a distribution, please invoke `configure WSL shortcuts` from the Start Menu subfolder WSLtty.
It seems I missed to mention that in the description on the project home page.

Yet I wonder why this message appears for you. Since you installed a Store version, the situation is different from issue 64; also there is a command prompt already visible behind the popup in the window in your screenshot. I'm afraid though I cannot debug that remotely. Please provide more precise information (how you installed/invoked/...) and try to reinstall.

**Comment by krazyito65** [comment]
So I had done a 'clean install' of windows, so everything was completely new.  I installed WSL from the windows store, set up everything I needed in the Ubuntu environment, I then installed 1.8.1, and I get this error.  I rand the 'configure' program and I still get the same error.

The command prompt in the background is simply the WSL from the windows store.  

How do I uninstall wsltty?  not really sure where it is.  Can I just use add/remove programs?

**Comment by krazyito65** [comment]
Oh.   I see.  I made a mistake I suppose.  I was suppose to run `Ubuntu Terminal %` instead of `WSL Terminal`

It works.  Sorry about that!

**Comment by mintty** [comment]
Or `Ubuntu Terminal` (without `%`), unless you want to start in your Windows documents folder.
Actually `WSL Terminal` should work as well, unless there is no "default distro" configured for you.
Please run the following from a Windows command console (Win+R cmd): `wslconfig /l` - what does it say?

**Comment by krazyito65** [comment]
`Windows Subsystem for Linux Distributions:
Ubuntu (Default)`

**Comment by mintty** [comment]
You may actually be running an older version of mintty within wsltty, if you installed while a wsltty session was open. I'll improve the installation to prevent that.

**Comment by pd93** [comment]
This issue popped up for me today.
I wanted to clean up my WSL environment, so I removed the Ubuntu app and reinstalled it. Unfortunately, I now get the same popup shown above when launching wsltty.
I've also tried re-installing wsltty with no success. Not sure what I should try next?

**Comment by mintty** [comment]
My previous suspicion was that an older wsltty installation would bear this bug, and installation of a newer version (1.8.1) may have failed unnoticed because a wsltty window was open during installation. (I've modified the installation procedure to try to avoid this.)
If this is not the case for you, I'm puzzled. Unfortunately, I don't see how I could debug it remotely.
Maybe you can try to reproduce the invocation command (as taken from the desktop/Start menu shortcut) on a Windows command line (Win+R cmd).

**Comment by pd93** [comment]
Hi, Thanks for the reply. I made sure that wsltty was fully closed before I updated. I've also tried manually removing the files in `%APPDATA%`, `%LOCALAPPDATA%` and the start menu.

Running the command from the shortcut directly in cmd gives the same result. I'm happy to do some debugging with you over a Skype (or similar) session if this is helpful? I'd really like to get this working again

**Comment by pd93** [comment]
I seem to have been able to resolve this after reading through the comments in #64.
I simply opened `cmd` and ran the command `wslconfig /s Ubuntu` and everything works again.

What's interesting is that prior to the above command, I tried `wslconfig /l` and it printed "Ubuntu (Default)". It seems like something somewhere was not set correctly and re-setting it has fixed whatever was wrong.

**Comment by mintty** [comment]
Thanks a lot for this valuable hint, I will include it somewhere in the README/project page.
Now I wonder what weird state you may have had before and whether it could be detected and repaired automatically. Any chance to revert to the broken state?
@krazyito65, can you please, before you fix the situation, export your relevant registry sub-trees?

**Comment by mintty** [comment]
> relevant registry sub-trees

That would be
`[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss]`
and, for the case of the Ubuntu distribution,
`[HKEY_CURRENT_USER\Software\Classes\Local Settings\Software\Microsoft\Windows\CurrentVersion\AppModel\SystemAppData\CanonicalGroupLimited.UbuntuonWindows_79rhkp1fndgsc]`

Run Windows tool `regedit`, navigate to the keys in the left panel, and on the respective key, right-click and select Export.

**Comment by pd93** [comment]
@mintty When I get home this evening, I will see if I can replicate the broken state. Is there anything you'd like me to check while I'm there? I'm not 100% this is even a wsltty issue?

So that it's documented here... I'll outline what I did to break it first time...
1. Enable WSL in Programs and Features
2. Install Ubuntu via the Windows App Store
3. Install wsltty v1.8.1. via the installer package
4. Uninstall Ubuntu via the Windows App Store
5. Reinstall Ubuntu via the Windows App Store
6. **Error message appears here**
7. Redownloading wsltty does not fix
8. Redownloading Ubuntu does not fix
9. Check output of `wslconfig /l` as a sanity check (Output is correct)
10. **Running `wslconfig /s Ubuntu` anyway fixes the error**

**Comment by krazyito65** [comment]
I actually don't have any problems now..  Ever since I started using `Ubuntu Terminal`.

Now when I open `WSL Terminal` it works fine as well

**Comment by mintty** [comment]
@pd93, if you can restore the broken state, first of all the registry state might be interesting.
If that doesn't give us a clue, I would add debug stuff into mintty, winmain.c, functions getlxssinfo and getlxssdistinfo, to see under which condition they actually return false. I could prepare a respective patch if that helps.

**Comment by mintty** [comment]
I've uploaded a debug enhancement, in case someone with the problem can self-compile mintty for wsltty (or run it from cygwin).

**Comment by mintty** [comment]
Released 1.8.2.
Please recheck. If the issue reoccurs, there should be at least better debug information.
