### ISSUE TITLE
Git config pointing to %APPDATA%/wsltty

### ISSUE THREAD

**Issue by pd93** [mintty/wsltty#76]
As Visual Studio Code [doesn't yet support WSL Git](https://github.com/Microsoft/vscode/issues/9502), I'm still having to use Git for Windows alongside WSL & WSLTTY. This is fine, but the problems start if I run `./git.exe --global --config` using either of the two `git.exe` files from Git for Windows. It reports the following error:

`fatal: unable to read config file 'C:/Users/myuser/AppData/Local/wsltty/home/myuser/.gitconfig': No such file or directory`

It's as if it thinks the wsltty install directory is the root of the filesystem and it's looking for my global git config in a non-existent home directory.

Running the same command from the same directory in Git Bash or cmd produce the correct results, which is what makes me think this is a WSLTTY issue.

To make matters weirder... when I open vscode from WSLTTY using the `code .` command, it brings up an instance of vscode with the wrong git config again.

**Comment by mintty** [comment]
Do you run Windows Git from WSL? Apparently, if a Windows application is started from WSL, it inherits the environment from the embedding Windows program, which is the terminal application mintty in this case.
To reproduce: Start cmd.exe from WSL and you'll see the %HOME% setting of mintty (even if that's not visible within WSL) which is due to mintty running in a standalone cygwin environment. I'm sure the same is happening to Windows Git if called from WSL.
To prevent this weird effect, I could explicitly unset HOME in mintty before invoking WSL.

As a workaround, you may try to copy your .gitconfig to where it's now expected. Do you actually need to call the --global --config for a build process? And what do you need VS for? (Which is kind of uncomforting me, for any dependencies this might cause.)

**Comment by mintty** [comment]
Mintty workaround tested and uploaded to repository.

**Comment by pd93** [comment]
So just to clarify my workflow here. I wouldn't normally call Windows Git from anywhere except indirectly by VS Code (as Windows Git is required for this currently - in fact, as soon as VS Code support WSL git, I shall be removing Windows Git completely). The actual reason that this is a problem for me, is that when I open a VS Code window via WSL (using `code .` in the terminal), VS Code seems to pick up the wrong git config. If I open VS Code via windows (not WSL), the config is correct.

The %HOME% variable could explain why this is happening. I'll try and compile your change myself and report back

**Comment by pd93** [comment]
@mintty Just tried to compile and I'm getting `cp: cannot stat 'themes.zoo': No such file or directory`. Am I missing some dependency or something? Just running `make` via Cygwin

**Comment by mintty** [comment]
Sorry, in the course of updating the wsltty build, I uploaded an inconsistent intermediate version.
Can you tweak the makefile for a workaround, or revert it to a previous commit?

**Comment by pd93** [comment]
So I managed to get it to build, but I'm still having the same issue. I get the feeling from the output of your Makefile, that it is using a downloaded zip of the mintty repo rather than my local version which has the change you made. This is also true when I run `make wsltty`. Is there a specific way to build wsltty with the local copy of mintty? .. or am I missing something entirely?

**Comment by mintty** [comment]
Please set the following in the wsltty makefile:
`minttyver=master`

**Comment by pd93** [comment]
Perfect! That seems to have solved the issue for me. I'll do a bit more testing over the next couple of days, but I'm happy to close this if you're happy with the fix.

**Comment by mintty** [comment]
Released 1.8.2.
