### ISSUE TITLE
How is wsltty > mintty + winpty?

### ISSUE THREAD

**Issue by mikeslattery** [mintty/wsltty#97]
I have Git-Bash installed.  I've been launching WSL with this shortcut:

```
"C:\Program Files\Git\usr\bin\mintty.exe"
    --exec /usr/bin/winpty
    "C:\Windows\System32\bash.exe"
    -c "cd ~; $SHELL --login -i
```

How and why is wsltty superior to the above?

**Comment by mintty** [comment]
wsltty uses wslbridge which is a dedicated variation of winpty with benefits in the handling of escape sequences, see rprichard/winpty#89 for the motivation to create wslbridge. So yes, it is superior.
Also, wsltty uses the cygwin build of mintty rather than the MSYS build used by Git bash.
With the MSYS build, pathname conversion for file open and drag-and-drop paste operations does not work properly.
As a package, wsltty adds preconfigured shortcuts for all WSL distributions, command line invocation scripts, and optional Explorer context menu integration.

**Comment by Biswa96** [comment]
Technically I think both ideas are same and has same background theory. Just wsltty has some extra care for users :) Am I right?

**Comment by mintty** [comment]
Not quite. Using winpty (rather than wslbridge) is discouraged because of limited support of terminal interaction (escape sequences).
wsltty is a cygwin-based standalone version for users who do not wish to install an explicit cygwin system, plus some extras. Mintty run as wsltty or from cygwin uses wslbridge in either case.
